project:
  type: website

website:
  title: "A Blog With Python Thanks to Quarto"
  draft-mode: unlinked
  navbar:
    left:
      - text: "Data blog"
        icon: pie-chart-fill
        href: data-blog.qmd
      - text: "Side projects"
        href: side-projects.qmd
        icon: joystick
    right:
      - text: "Coffee blog"
        icon: cup-hot-fill
        href: coffee-blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer:
    left: |
          This blog was written by Charlotte Hadley
          <br>I hope you enjoy it!
    center:
     - text: "This works in the same way as the navbar"
       icon: info-circle-fill
    right:
     - icon: github
       href: https://github.com/charliejhadley/create-your-own-data-blog-with-quarto-and-python-5968001
       aria-label: GitHub Repo
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



