project:
  type: website

website:
  title: "A Blog With Python Thanks to Quarto"
  draft-mode: unlinked
  navbar:
    left:
      - text: "Data blog"
        icon: pie-chart-fill
        href: data-blog.qmd
      - text: "Side projects"
        href: side-projects.qmd
        icon: joystick
    right:
      - text: "Coffee blog"
        icon: cup-hot-fill
        href: coffee-blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



